/**
||      Filename: A+B-Problem.c
||  
||  Description
||		Problem Description
||		A simple mathematical formula for e is
||
||		where n is allowed to go to infinity. This can actually yield very accurate approximations of e using relatively small values of n.
||		 
||		Output
||		Output the approximations of e generated by the above formula for the values of n from 0 to 9. The beginning of your output should appear similar to that shown below.
||		 
||		Sample Output
||		n e
||		- -----------
||		0 1
||		1 2
||		2 2.5
||		3 2.666666667
||		4 2.708333333
||
||      Version: 1.0
||      Reversion: none
||		complier: gcc
||      Created: 2016-03-26 13:01:38
||      Author: JackDan9(https://www.github.com/JackDan9) J.Dan92016@gmail.com
*/
#include <stdio.h>
int main()
{
	int i;
	double s=2.5,a=0.5;
	printf("n e\n");
	printf("- -----------\n");
	printf("0 1\n");
	printf("1 2\n");
	printf("2 2.5\n");
	for(i=3;i<10;i++)
	{
		a/=i;
		s+=a;
		printf("%d %.9f\n",i,s);
	}
	return 0;
}